In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as  plt

In [2]:
df= pd.read_csv('/kaggle/input/marketing-linear-multiple-regression/Marketing_Data.csv')

In [3]:
df.head()

youtube  facebook  newspaper  sales
0    84.72     19.20      48.96  12.60
1   351.48     33.96      51.84  25.68
2   135.48     20.88      46.32  14.28
3   116.64      1.80      36.00  11.52
4   318.72     24.00       0.36  20.88

In [4]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
x

array([[ 84.72,  19.2 ,  48.96],
       [351.48,  33.96,  51.84],
       [135.48,  20.88,  46.32],
       [116.64,   1.8 ,  36.  ],
       [318.72,  24.  ,   0.36],
       [114.84,   1.68,   8.88],
       [348.84,   4.92,  10.2 ],
       [320.28,  52.56,   6.  ],
       [ 89.64,  59.28,  54.84],
       [ 51.72,  32.04,  42.12],
       [273.6 ,  45.24,  38.4 ],
       [243.  ,  26.76,  37.92],
       [212.4 ,  40.08,  46.44],
       [352.32,  33.24,   2.16],
       [248.28,  10.08,  31.68],
       [ 30.12,  30.84,  51.96],
       [210.12,  27.  ,  37.8 ],
       [107.64,  11.88,  42.84],
       [287.88,  49.8 ,  22.2 ],
       [272.64,  18.96,  59.88],
       [ 80.28,  14.04,  44.16],
       [239.76,   3.72,  41.52],
       [120.48,  11.52,   4.32],
       [259.68,  50.04,  47.52],
       [219.12,  55.44,  70.44],
       [315.24,  34.56,  19.08],
       [238.68,  59.28,  72.  ],
       [  8.76,  33.72,  49.68],
       [163.44,  23.04,  19.92],
       [252.96,  59.52,  45.24],
       [25

In [6]:
y

array([12.6 , 25.68, 14.28, 11.52, 20.88, 11.4 , 15.36, 30.48, 17.64,
       12.12, 25.8 , 19.92, 20.52, 24.84, 15.48, 10.2 , 17.88, 12.72,
       27.84, 17.76, 11.64, 13.68, 12.84, 27.12, 25.44, 24.24, 28.44,
        6.6 , 15.84, 28.56, 22.08,  9.72, 29.04, 18.84, 16.8 , 21.6 ,
       11.16, 11.4 , 16.08, 22.68, 26.76, 21.96, 14.88, 10.56, 13.2 ,
       20.4 , 10.44,  8.28, 17.04,  6.36, 13.2 , 14.16, 14.76, 13.56,
       16.32, 26.04, 18.24, 14.4 , 19.2 , 15.48, 20.04, 13.44,  8.76,
       23.28, 26.64, 13.8 , 20.28, 14.04, 18.6 , 30.48, 20.64, 14.04,
       28.56, 17.76, 17.64, 24.84, 23.04,  8.64, 10.44,  6.36, 23.76,
       16.08, 26.16, 16.92, 19.08, 17.52, 15.12, 14.64, 11.28, 19.08,
        7.92, 18.6 ,  8.4 , 13.92, 18.24, 23.64, 12.72,  7.92, 10.56,
       29.64, 11.64,  1.92, 15.24,  6.84, 23.52, 12.96, 13.92, 11.4 ,
       24.96, 11.52, 24.84, 13.08, 23.04, 24.12, 12.48, 13.68, 12.36,
       15.84, 30.48, 13.08, 12.12, 19.32, 13.92, 19.92, 22.8 , 18.72,
        3.84, 18.36,

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
x_train

array([[155.28,   6.84,  37.56],
       [306.48,  32.28,   6.6 ],
       [ 30.72,  46.8 ,  11.16],
       [ 96.24,   0.  ,  11.04],
       [212.4 ,  11.16,   7.68],
       [219.12,  55.44,  70.44],
       [252.84,  35.4 ,  11.16],
       [ 22.56,  26.04,  60.48],
       [ 88.08,  20.4 ,  15.48],
       [ 67.44,   6.84,  35.64],
       [272.64,  18.96,  59.88],
       [102.84,  42.96,  59.16],
       [225.48,  20.64,  21.48],
       [ 22.44,  14.52,  28.08],
       [210.12,  27.  ,  37.8 ],
       [145.2 ,  10.08,  58.44],
       [340.32,  50.4 ,  79.44],
       [260.16,  52.68,  32.64],
       [262.2 ,   6.48,  32.88],
       [120.48,  11.52,   4.32],
       [ 57.96,  56.4 ,  10.2 ],
       [304.56,  25.56,  36.  ],
       [205.56,  47.64,  45.24],
       [266.88,   5.16,  59.76],
       [167.4 ,   2.52,  31.92],
       [232.44,  42.48,  90.72],
       [  8.76,  33.72,  49.68],
       [332.04,   2.76,  28.44],
       [207.  ,  21.72,  36.84],
       [104.64,  14.16,  31.08],
       [16

In [9]:
x_test

array([[ 82.08,  53.4 ,  42.72],
       [266.88,   4.08,  15.72],
       [261.24,  40.2 ,  70.8 ],
       [256.2 ,  51.6 ,  40.56],
       [225.36,  25.32,  11.4 ],
       [ 71.52,  14.4 ,  51.72],
       [320.28,  52.56,   6.  ],
       [345.12,  51.6 ,  86.16],
       [263.76,  40.2 ,  54.12],
       [150.84,  44.28,  95.04],
       [ 21.48,  45.12,  25.92],
       [202.08,   8.52,  15.36],
       [114.84,   1.68,   8.88],
       [  9.36,  46.68,  60.72],
       [ 90.6 ,  12.96,   7.2 ],
       [268.8 ,   2.88,  18.72],
       [287.16,  18.6 ,  32.76],
       [287.88,  49.8 ,  22.2 ],
       [161.16,   5.88,  11.16],
       [ 91.68,  32.04,  26.76],
       [195.96,  37.92,  63.48],
       [ 37.8 ,  29.52,   2.64],
       [318.72,  24.  ,   0.36],
       [291.84,  58.8 ,  53.16],
       [131.76,  57.36,  61.68],
       [ 51.6 ,  31.08,  24.6 ],
       [237.12,  27.96,  17.04],
       [248.16,   6.24,  23.28],
       [221.88,  52.68,   2.04],
       [229.32,  34.44,  21.84],
       [23

In [10]:
y_train

array([13.2 , 23.76, 11.4 , 10.56, 15.36, 25.44, 22.08,  8.4 , 13.08,
       10.44, 17.76, 15.96, 17.64,  8.04, 17.88, 13.92, 30.6 , 26.76,
       14.64, 12.84, 13.92, 21.12, 22.8 , 14.04, 12.36, 23.04,  6.6 ,
       14.16, 17.28, 12.72, 12.36, 15.12,  8.76, 14.28, 15.48, 18.24,
       23.64, 10.56, 25.8 , 16.92, 17.76, 20.76, 24.96,  1.92,  7.92,
       14.28, 23.52, 13.2 , 24.12, 27.12, 26.64, 13.08, 19.32, 30.48,
        6.36, 17.04, 17.52, 24.84, 15.48, 27.12, 10.08, 11.64, 10.2 ,
       10.44, 14.76, 23.04, 11.52, 16.08,  8.76, 15.36, 18.6 , 24.84,
       19.08, 21.6 , 20.52, 17.88, 32.4 , 15.48, 12.6 , 18.6 , 24.24,
       10.44, 19.92, 15.24, 21.6 , 14.4 , 21.96, 11.64, 13.8 , 25.68,
       12.12, 20.52, 19.08, 14.88, 12.96, 15.12, 12.72, 16.08, 13.56,
       14.28, 12.12, 16.8 , 15.84, 12.48,  9.72,  9.12, 18.36, 12.6 ,
       29.04, 17.4 , 28.56, 29.64, 26.16,  6.36, 13.68, 14.04,  9.12,
       28.56,  8.64, 24.24, 16.08, 12.96,  7.08, 22.68, 19.2 , 18.  ,
       11.28, 20.64,

In [11]:
y_test

array([16.32, 13.8 , 23.28, 26.04, 18.72, 11.64, 30.48, 31.44, 23.52,
       19.08,  9.6 , 14.04, 11.4 ,  7.92, 11.88, 13.92, 18.84, 27.84,
       13.44, 14.16, 20.28, 11.4 , 20.88, 30.48, 20.04, 11.52, 19.92,
       14.64, 24.84, 20.76, 28.44, 18.24,  3.84, 20.4 , 17.64])

In [12]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=reg.predict(x_test)

In [14]:
y_pred

array([17.47637032, 16.37438329, 23.03375348, 24.76366742, 18.44000541,
        9.88587684, 27.58148165, 28.87880859, 23.06393669, 19.0636305 ,
       13.21803757, 14.34999561,  9.23890874, 13.14124811, 10.24291776,
       16.2522827 , 20.0147228 , 25.73237296, 12.05155149, 13.89264368,
       19.7192218 , 10.95264453, 22.23454235, 27.70965086, 20.47231834,
       11.94972356, 19.4677982 , 15.98774074, 23.2733346 , 20.3406546 ,
       25.5594432 , 18.45251872,  6.66383729, 20.57898229, 18.94707082])

In [15]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[17.48 16.32]
 [16.37 13.8 ]
 [23.03 23.28]
 [24.76 26.04]
 [18.44 18.72]
 [ 9.89 11.64]
 [27.58 30.48]
 [28.88 31.44]
 [23.06 23.52]
 [19.06 19.08]
 [13.22  9.6 ]
 [14.35 14.04]
 [ 9.24 11.4 ]
 [13.14  7.92]
 [10.24 11.88]
 [16.25 13.92]
 [20.01 18.84]
 [25.73 27.84]
 [12.05 13.44]
 [13.89 14.16]
 [19.72 20.28]
 [10.95 11.4 ]
 [22.23 20.88]
 [27.71 30.48]
 [20.47 20.04]
 [11.95 11.52]
 [19.47 19.92]
 [15.99 14.64]
 [23.27 24.84]
 [20.34 20.76]
 [25.56 28.44]
 [18.45 18.24]
 [ 6.66  3.84]
 [20.58 20.4 ]
 [18.95 17.64]]


In [16]:
print(reg.coef_)
print(reg.intercept_)

[0.04 0.18 0.  ]
3.855843431588161


In [17]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

3.4897781691644782